### ISSUE TITLE
Striped Barrucada/Sea Pike found in frame 04C2_Luderick_16_004800.jpg

### ISSUE THREAD

**Issue by BenMaslen** [globalwetlands/luderick-seagrass#2]
It seems in some frames, (for instance in 04C2_Luderick_16_004800.jpg) other fish are present besides bream or luderick with this not being recorded anywhere (as far as I can see in the luderick_seagrass_all.csv or luderick_seagrass_jack_evans_b.csv files). 

![04C2_Luderick_16_004800](https://user-images.githubusercontent.com/46333799/154875941-9e5a7aa0-4d3f-423c-9465-d76c28afb978.jpg)

I was wondering if there is a table somewhere you could add to the repository which may atleast have an ID for which frames have other fish present in them besides Luderick or Bream?

**Comment by elditria** [comment]
Hi Ben! When we were annotating these images it was to focus on the one species (luderick). We unfortunately did not note the other species in the frames at the time and have not documented these anywhere. Unfortunately due to the amount of work this would take manually going through the data we wont be able to provide that information.

**Comment by CexyNature** [comment]
@BenMaslen thanks for your input. I am closing this issue as per Ellen’s reply. @BenMaslen if you think your suggestion adds value to this dataset, please consider opening a Pull Request with your suggested updates, and we would be happy to review it.
